### ISSUE TITLE
Authorize attribute on basic (non-Auth) TraderSys sample causes error.

### ISSUE THREAD

**Issue by zackJKnight** [dotnet-architecture/grpc-for-wcf-developers#1]
The sample could be more approachable if you remove [the Authorize attribute from PortfolioService.cs](https://github.com/dotnet-architecture/grpc-for-wcf-developers/blob/73d0f7db3338326bc4b798cbb62c4d6b31f98f26/PortfoliosSample/grpc/TraderSys/src/TraderSys.Portfolios/Services/PortfolioService.cs#L20)

I get this exception when I run the sample:

```
   at Grpc.Net.Client.Internal.GrpcCall`2.ValidateHeaders()
   at Grpc.Net.Client.Internal.GrpcCall`2.<SendAsync>d__76.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.GrpcCall`2.<GetResponseHeadersAsync>d__67.MoveNext()
```

And the output clued me in that authorization is expected:

```
System.InvalidOperationException: Endpoint gRPC - /PortfolioService.Portfolios/Get contains authorization metadata, but a middleware was not found that supports authorization.
Configure your application startup by adding app.UseAuthorization() inside the call to Configure(..) in the application startup code. The call to app.UseAuthorization() must appear between app.UseRouting() and app.UseEndpoints(...).
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by umitkavala** [comment]
Same here. I've removed Authorized attribute to run example.

**Comment by VaishaliRaval** [comment]
Hey @zackJKnight and @umitkavala Thanks for pointing it out. We have removed the Authorize attribute from the non-Auth TraderSys sample. Closing this issue.
